---
title: "Revisions notebook"
author: "Joe Oddy"
lightbox: auto
execute:
  echo: false
  warning: false
  dev: "ragg_png"
  cache: false
format:
  html:
    theme: flatly
    mermaid:
      theme: neutral
    page-layout: article
    self-contained: true
    code-line-numbers: true
    code-block-bg: true
    code-block-border-left: "#30BBF0"
    code-copy: true
    code-link: false
    code-fold: true
    code-tools:
      source: true
      toggle: false
      caption: none
    fig-align: center
    fig-height: 5
    fig-width: 8
    fig-responsive: true
    fig-dpi: 600
    fig-cap-location: top
    number-sections: true
    number-depth: 2
    toc: true
    toc-depth: 3
    dev: "ragg_png"
    smooth-scroll: true
    embed-resources: true
---

# Loading

```{r}
#| label: library-loading

library(tidyverse)
library(here)
library(aqua)
library(umap)
library(mixOmics)
# mixKernel has quite a few dependencies, see mixKernel installation guide
library(conflicted)
library(janitor)
library(gt)
library(arrow)
library(patchwork)
conflicts_prefer(dplyr::filter)
conflicts_prefer(dplyr::rename)
conflicts_prefer(dplyr::select)
conflicts_prefer(dplyr::lag)
conflicts_prefer(dplyr::desc)
conflicts_prefer(aqua::rescale)
conflicts_prefer(arrow::read_feather)
conflicts_prefer(base::as.factor)
conflicted::conflicts_prefer(dplyr::first)

source(here("01_scripts/helpers.R"))
```


# Correlations between scRNA and flow cytometry
```{r}
raw_process_data <- fetch_rds("https://raw.githubusercontent.com/cgtc/plasticell_flow_analysis/main/00_data/multiomics_process_data/raw_process_data.rds")

r3_fcm_target_variable <- raw_process_data[["r3_process_data"]]

r4_fcm_target_variable <- raw_process_data[["r4_process_data"]]

write.csv(r3_fcm_target_variable, here("00_data", "fcm_nk_cell_percentages_run_3.csv"), row.names = FALSE)
write.csv(r4_fcm_target_variable, here("00_data", "fcm_nk_cell_percentages_run_4.csv"), row.names = FALSE)

```

```{r}
r3_cd45_cd56 <- r3_fcm_target_variable |> 
    # select only rows with suspension as cell portion
    filter(`Cell portion` == "Suspension") |> 
    # select only the columns we need
    select(Label, "CD45+/CD56+ (%)...63", "CD45+/CD56+ (%)...64") |> 
    # calculate mean of those two columns
    mutate(proportion_NK = rowMeans(pick("CD45+/CD56+ (%)...63", "CD45+/CD56+ (%)...64"), na.rm = TRUE)) |>
    drop_na(proportion_NK)

r4_cd45_cd56 <- r4_fcm_target_variable |> 
    # select only rows with suspension as cell portion
    filter(`Cell portion` == "Suspension") |> 
    # select only the columns we need
    select(Label, "CD45+/CD56+ (%)...63", "CD45+/CD56+ (%)...64") |> 
    # calculate mean of those two columns
    mutate(proportion_NK = rowMeans(pick("CD45+/CD56+ (%)...63", "CD45+/CD56+ (%)...64"), na.rm = TRUE)) |>
    drop_na(proportion_NK)

cd45_cd56_data <- r3_cd45_cd56 |> 
    bind_rows(r4_cd45_cd56) |> 
    select(Label, proportion_NK)
```


```{r}
run_3_scrna_identity <- read_csv(here("00_data", "nk_cell_percentages_run_3.csv")) |> 
    mutate(run = 3) |> 
    # extract vessel number from string like "V01" but only the number as numeric
    mutate(vessel = as.numeric(str_extract(vessel_day, "(?<=V)\\d+"))) |> 
    # extract day number from string like "D1" or "D35" but only the number as numeric
    mutate(day = as.numeric(str_extract(vessel_day, "(?<=D)\\d+"))) |> 
    # make labels like r3_v4_d6
    mutate(label = paste0("r", run, "_v", vessel, "_d", day))

run_4_scrna_identity <- read_csv(here("00_data", "nk_cell_proportions_run_4.csv")) |> 
    mutate(run = 4) |> 
    # extract vessel number from string like "V01" but only the number as numeric
    mutate(vessel = as.numeric(str_extract(vessel_day, "(?<=V)\\d+"))) |> 
    # extract day number from string like "D1" or "D35" but only the number as numeric
    mutate(day = as.numeric(str_extract(vessel_day, "(?<=D)\\d+"))) |> 
    # make labels like r3_v4_d6
    mutate(label = paste0("r", run, "_v", vessel, "_d", day))

scrna_target_variable <- run_3_scrna_identity |> 
    select(label, vessel, day, proportion_NK) |> 
    bind_rows(run_4_scrna_identity |> 
        select(label, vessel, day, proportion_NK))
```

```{r}
cd45_cd56_scrna_data <- scrna_target_variable |> 
    select(label, proportion_NK) |> 
    inner_join(cd45_cd56_data, by = c("label" = "Label"), suffix = c("_scrna", "_fcm")) |> 
    rename(proportion_NK_scrna = proportion_NK_scrna, proportion_NK_fcm = proportion_NK_fcm)

# calculate the strength of the correlation between the two methods
correlation <- cor(cd45_cd56_scrna_data$proportion_NK_scrna, cd45_cd56_scrna_data$proportion_NK_fcm, method = "pearson")
```

```{r}
cd45_cd56_correlation_plot <- ggplot(cd45_cd56_scrna_data, aes(x = proportion_NK_scrna, y = proportion_NK_fcm)) +
    geom_point() +
    geom_smooth(method = "lm", se = FALSE, color = "blue") +
    labs(title = paste("Correlation between scRNA and flow cytometry"),
         x = "Proportion of NK cells (scRNA)",
         y = "Proportion of CD45+/CD56+ cells (flow cytometry)") +
            # add correlation coefficient to plot in corner
    annotate("text", x = 0, y = 0.9, label = paste("r =", round(correlation, 2)), hjust = 0, size = 5) +
    theme_catapult()

cd45_cd56_correlation_plot
```

```{r}
# bland altman plot with loa lines
bland_altman <- ggplot(cd45_cd56_scrna_data, aes(x = (proportion_NK_scrna + proportion_NK_fcm) / 2, y = proportion_NK_scrna - proportion_NK_fcm)) +
    geom_point() +
    geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
    geom_hline(yintercept = mean(cd45_cd56_scrna_data$proportion_NK_scrna - cd45_cd56_scrna_data$proportion_NK_fcm), linetype = "dashed", color = "blue") +
    geom_hline(yintercept = mean(cd45_cd56_scrna_data$proportion_NK_scrna - cd45_cd56_scrna_data$proportion_NK_fcm) + 1.96 * sd(cd45_cd56_scrna_data$proportion_NK_scrna - cd45_cd56_scrna_data$proportion_NK_fcm), linetype = "dotted", color = "blue") +
    geom_hline(yintercept = mean(cd45_cd56_scrna_data$proportion_NK_scrna - cd45_cd56_scrna_data$proportion_NK_fcm) - 1.96 * sd(cd45_cd56_scrna_data$proportion_NK_scrna - cd45_cd56_scrna_data$proportion_NK_fcm), linetype = "dotted", color = "blue") +
    labs(title = "Bland-Altman plot (scRNA and flow cytometry)",
         x = "Average of scRNA and flow cytometry",
         y = "Difference between scRNA and flow cytometry") +
    theme_catapult()

bland_altman
# calculate average difference and limits of agreement
mean_diff <- mean(cd45_cd56_scrna_data$proportion_NK_scrna - cd45_cd56_scrna_data$proportion_NK_fcm)
loa_upper <- mean_diff + 1.96 * sd(cd45_cd56_scrna_data$proportion_NK_scrna - cd45_cd56_scrna_data$proportion_NK_fcm)
loa_lower <- mean_diff - 1.96 * sd(cd45_cd56_scrna_data$proportion_NK_scrna - cd45_cd56_scrna_data$proportion_NK_fcm)
```

```{r}
#| fig-width: 10
#| fig-height: 10

# plot together with patchwork with labels A. and B. with one column two rows, make each plot square
combined_plot <- (cd45_cd56_correlation_plot + theme(aspect.ratio = 1)) / (bland_altman + theme(aspect.ratio = 1)) + plot_annotation(tag_levels = 'A')
combined_plot
```

# Visualisation of NK cell purity

```{r}
#| fig-width: 6
#| fig-height: 12

scrna_target_variable |> 
    mutate(run = str_extract(label, "(?<=r)\\d+")) |>
    ggplot(aes(x = day, y = proportion_NK)) +
    facet_grid(vessel ~ run) +
    geom_point() +
    geom_line() +
    labs(title = "Proportion of NK cells over time (scRNA)",
         x = "Day",
         y = "Proportion of NK cells",
         color = "Vessel") +
    theme_catapult()
```


```{r}
#| fig-width: 6
#| fig-height: 4

# histogram showing distribution of NK cell proportions coloured by run
scrna_target_variable |> 
    mutate(run = str_extract(label, "(?<=r)\\d+")) |>
    ggplot(aes(x = proportion_NK)) +
    facet_wrap(~ run, ncol = 2) +
    geom_histogram(binwidth = 0.05) +
    labs(title = "Distribution of NK cell proportions (scRNA)",
         x = "Proportion of NK cells",
         y = "Count") +
    theme_catapult()
```


```{r}

```